import { Member, ClassUnit, SabbathDate, ManaSubscription, RollCallRecord, SyncConfig, CriteriaPointsConfig, LessonCatalogItem, UnitWeeklyData } from './types';

export const INITIAL_CLASSES: ClassUnit[] = [
  {
    id: 'cls-1',
    name: 'Ebenézer',
    category: 'Adultos',
    teacher1Id: 'mb-1',
    teacher1Name: 'Adriana Silva',
    teacher2Id: 'mb-4',
    teacher2Name: 'Pr. Ricardo Santos',
    room: 'Sala Principal - Térreo',
    memberCount: 22,
    targetOffering: 100.0,
  },
  {
    id: 'cls-2',
    name: 'Maranata',
    category: 'Adultos',
    teacher1Id: 'mb-5',
    teacher1Name: 'Bruno Oliveira',
    teacher2Id: 'mb-6',
    teacher2Name: 'Camila Fernandes',
    room: 'Sala 02 - Galeria',
    memberCount: 18,
    targetOffering: 80.0,
  },
  {
    id: 'cls-3',
    name: 'Bereia',
    category: 'Adultos',
    teacher1Id: 'mb-7',
    teacher1Name: 'Diego Martins',
    teacher2Id: 'mb-8',
    teacher2Name: 'Elena Costa',
    room: 'Sala 03',
    memberCount: 19,
    targetOffering: 75.0,
  },
  {
    id: 'cls-4',
    name: 'Jovens - Geração Eleita',
    category: 'Jovens',
    teacher1Id: 'mb-9',
    teacher1Name: 'Fernando Lima',
    teacher2Id: 'mb-10',
    teacher2Name: 'Gabriel Rocha',
    room: 'Auditório Jovem',
    memberCount: 25,
    targetOffering: 60.0,
  },
  {
    id: 'cls-5',
    name: 'Adolescentes - Teen Zone',
    category: 'Adolescentes',
    teacher1Id: 'mb-11',
    teacher1Name: 'Heloísa Ribeiro',
    teacher2Id: '',
    teacher2Name: '',
    room: 'Sala Teen',
    memberCount: 14,
    targetOffering: 40.0,
  },
  {
    id: 'cls-6',
    name: 'Primários & Infantil',
    category: 'Infantil',
    teacher1Id: 'mb-12',
    teacher1Name: 'Juliana Mendes',
    teacher2Id: '',
    teacher2Name: '',
    room: 'Sala das Crianças',
    memberCount: 12,
    targetOffering: 30.0,
  },
];

export const INITIAL_UNIT_WEEKLY_DATA: UnitWeeklyData[] = [
  {
    id: 'uwd-2026-01-03-cls-1',
    sabbathDate: '2026-01-03',
    unitOrClassId: 'cls-1',
    unitName: 'Ebenézer',
    extraPoints: 20,
    offeringTarget: 100.0,
    offeringCollected: 120.0,
  },
  {
    id: 'uwd-2026-01-03-cls-2',
    sabbathDate: '2026-01-03',
    unitOrClassId: 'cls-2',
    unitName: 'Maranata',
    extraPoints: 15,
    offeringTarget: 80.0,
    offeringCollected: 80.0,
  },
];

export const INITIAL_MEMBERS: Member[] = [
  {
    id: 'mb-1',
    name: 'Adriana Silva',
    type: 'Membro',
    status: 'Ativo',
    className: 'Ebenézer',
    unit: 'Unidade 1',
    isTeacher: true,
    age: 30,
    gender: 'Fem',
    phone: '(11) 98765-4321',
    email: 'adriana.silva@email.com',
    address: 'Rua das Flores, 120 - São Paulo',
    createdAt: '2024-01-10',
  },
  {
    id: 'mb-2',
    name: 'Alba Regina',
    type: 'Membro',
    status: 'Inativo',
    className: 'Ebenézer',
    unit: 'Unidade 5',
    isTeacher: false,
    age: 45,
    gender: 'Fem',
    phone: '(11) 97123-8899',
    email: 'alba.regina@email.com',
    createdAt: '2024-02-15',
  },
  {
    id: 'mb-3',
    name: 'Carlos Eduardo Souza',
    type: 'Visitante',
    status: 'Visitante',
    className: 'Maranata',
    unit: 'Unidade 2',
    isTeacher: false,
    age: 28,
    gender: 'Masc',
    phone: '(11) 96543-2109',
    createdAt: '2026-01-10',
  },
  {
    id: 'mb-4',
    name: 'Pr. Ricardo Santos',
    type: 'Membro',
    status: 'Ativo',
    className: 'Ebenézer',
    unit: 'Unidade 1',
    isTeacher: true,
    age: 52,
    gender: 'Masc',
    phone: '(11) 99887-6655',
    email: 'ricardo.santos@igreja.org',
    createdAt: '2023-08-01',
  },
  {
    id: 'mb-5',
    name: 'Bruno Oliveira',
    type: 'Membro',
    status: 'Ativo',
    className: 'Maranata',
    unit: 'Unidade 2',
    isTeacher: true,
    age: 36,
    gender: 'Masc',
    phone: '(11) 98456-7788',
    createdAt: '2024-03-20',
  },
  {
    id: 'mb-6',
    name: 'Camila Fernandes',
    type: 'Membro',
    status: 'Ativo',
    className: 'Maranata',
    unit: 'Unidade 2',
    isTeacher: true,
    age: 32,
    gender: 'Fem',
    phone: '(11) 97321-4455',
    createdAt: '2024-04-12',
  },
  {
    id: 'mb-7',
    name: 'Diego Martins',
    type: 'Membro',
    status: 'Ativo',
    className: 'Bereia',
    unit: 'Unidade 3',
    isTeacher: true,
    age: 41,
    gender: 'Masc',
    phone: '(11) 99112-3344',
    createdAt: '2023-11-05',
  },
  {
    id: 'mb-8',
    name: 'Elena Costa',
    type: 'Membro',
    status: 'Afastado',
    className: 'Bereia',
    unit: 'Unidade 3',
    isTeacher: false,
    age: 39,
    gender: 'Fem',
    phone: '(11) 98223-4455',
    createdAt: '2024-01-18',
  },
  {
    id: 'mb-9',
    name: 'Fernando Lima',
    type: 'Membro',
    status: 'Ativo',
    className: 'Jovens - Geração Eleita',
    unit: 'Unidade Jovem',
    isTeacher: true,
    age: 24,
    gender: 'Masc',
    phone: '(11) 97445-6677',
    createdAt: '2024-06-01',
  },
  {
    id: 'mb-10',
    name: 'Gabriel Rocha',
    type: 'Membro',
    status: 'Ativo',
    className: 'Jovens - Geração Eleita',
    unit: 'Unidade Jovem',
    isTeacher: false,
    age: 22,
    gender: 'Masc',
    phone: '(11) 96554-3322',
    createdAt: '2024-07-10',
  },
  {
    id: 'mb-11',
    name: 'Heloísa Ribeiro',
    type: 'Membro',
    status: 'Ativo',
    className: 'Adolescentes - Teen Zone',
    unit: 'Unidade Teen',
    isTeacher: true,
    age: 16,
    gender: 'Fem',
    phone: '(11) 99881-2233',
    createdAt: '2025-01-15',
  },
  {
    id: 'mb-12',
    name: 'Juliana Mendes',
    type: 'Membro',
    status: 'Ativo',
    className: 'Primários & Infantil',
    unit: 'Unidade Infantil',
    isTeacher: true,
    age: 29,
    gender: 'Fem',
    phone: '(11) 97766-5544',
    createdAt: '2024-09-02',
  },
  {
    id: 'mb-13',
    name: 'Lucas Barbosa',
    type: 'Visitante',
    status: 'Visitante',
    className: 'Jovens - Geração Eleita',
    unit: 'Unidade Jovem',
    age: 25,
    gender: 'Masc',
    phone: '(11) 95544-3322',
    createdAt: '2026-02-01',
  },
  {
    id: 'mb-14',
    name: 'Mariana Pires',
    type: 'Membro',
    status: 'Inativo',
    className: 'Ebenézer',
    unit: 'Unidade 5',
    age: 50,
    gender: 'Fem',
    phone: '(11) 98877-1122',
    createdAt: '2023-05-14',
  },
];

// Generate 52 Saturdays of 2026 (Escala Informativa de Escola Sabatina por Departamento e Diretor)
export const SABBATHS_2026: SabbathDate[] = [
  // Q1 2026 (Escala Trimestral)
  { date: '2026-01-03', formattedDate: '03/Jan/2026', quarter: 1, sabbathNumberInQuarter: 1, department: 'Escola Sabatina', directorName: 'Bruna Silva', notes: 'Abertura do trimestre e recepção dos professores.' },
  { date: '2026-01-10', formattedDate: '10/Jan/2026', quarter: 1, sabbathNumberInQuarter: 2, department: 'Ministério Pessoal', directorName: 'Fernandes Ramos', notes: 'Treinamento e motivação para duplas missionárias.', targetOffering: 1500 },
  { date: '2026-01-17', formattedDate: '17/Jan/2026', quarter: 1, sabbathNumberInQuarter: 3, department: 'Diaconisas', directorName: 'Aliny Franca', notes: 'Organização e ordem na recepção e templo.' },
  { date: '2026-01-24', formattedDate: '24/Jan/2026', quarter: 1, sabbathNumberInQuarter: 4, department: 'Ministério da Comunicação', directorName: 'Nalbert Vitor', notes: 'Divulgação dos projetos da igreja e redes.' },
  { date: '2026-01-31', formattedDate: '31/Jan/2026', quarter: 1, sabbathNumberInQuarter: 5, department: 'Ministério da Saúde', directorName: 'Edney de Araújo', specialEvent: 'Sábado de Ação de Graças', notes: 'Momento de oração, saúde e testemunhos.' },
  { date: '2026-02-07', formattedDate: '07/Fev/2026', quarter: 1, sabbathNumberInQuarter: 6, department: 'Pequenos Grupos', directorName: 'Assunção', notes: 'Encontro e testemunhos dos Pequenos Grupos.' },
  { date: '2026-02-14', formattedDate: '14/Fev/2026', quarter: 1, sabbathNumberInQuarter: 7, department: 'Retiro', directorName: 'Bruna Silva', notes: 'Programação especial espiritual de retiro.' },
  { date: '2026-02-21', formattedDate: '21/Fev/2026', quarter: 1, sabbathNumberInQuarter: 8, department: 'Ministério de Publicações', directorName: 'Mattheus', notes: 'Incentivo à literatura espiritual e colportagem.' },
  { date: '2026-02-28', formattedDate: '28/Fev/2026', quarter: 1, sabbathNumberInQuarter: 9, department: 'Ministério da Mulher', directorName: 'Aliny França', specialEvent: 'Dia do Jovem Adventista', notes: 'Ação integrada com o Ministério da Mulher.' },
  { date: '2026-03-07', formattedDate: '07/Mar/2026', quarter: 1, sabbathNumberInQuarter: 10, department: 'Ministério de Recepção', directorName: 'Marlete Moraes', notes: 'Recepção calorosa e integração de novos amigos.' },
  { date: '2026-03-14', formattedDate: '14/Mar/2026', quarter: 1, sabbathNumberInQuarter: 11, department: 'Ministério de Mordomia Cristã', directorName: 'Walter Garces', notes: 'Reflexão sobre fidelidade e mordomia espiritual.' },
  { date: '2026-03-21', formattedDate: '21/Mar/2026', quarter: 1, sabbathNumberInQuarter: 12, department: 'Ministério dos Jovens (JA)', directorName: 'Nalbert Vitor', notes: 'Louvor e programa jovem na Escola Sabatina.' },
  { date: '2026-03-28', formattedDate: '28/Mar/2026', quarter: 1, sabbathNumberInQuarter: 13, department: 'Ministério dos Adolescentes', directorName: 'Marcio Victor', specialEvent: 'Programa de 13º Sábado', notes: 'Celebração de encerramento do trimestre e oferta especial.', targetOffering: 3500 },

  // Q2 2026
  { date: '2026-04-04', formattedDate: '04/Abr/2026', quarter: 2, sabbathNumberInQuarter: 1, department: 'Escola Sabatina & Recepção', directorName: 'Marcos Silva', notes: 'Abertura do 2º Trimestre e renovação de metas.' },
  { date: '2026-04-11', formattedDate: '11/Abr/2026', quarter: 2, sabbathNumberInQuarter: 2, department: 'Publicações & Espirito de Profecia', directorName: 'Fernando Lima', notes: 'Incentivo à leitura e literatura bíblica.' },
  { date: '2026-04-18', formattedDate: '18/Abr/2026', quarter: 2, sabbathNumberInQuarter: 3, department: 'Ministério da Mulher', directorName: 'Adriana Silva', notes: 'Momentos de oração e testemunhos.' },
  { date: '2026-04-25', formattedDate: '25/Abr/2026', quarter: 2, sabbathNumberInQuarter: 4, department: 'Ação Solidária Adventista (ASA)', directorName: 'Diego Martins', notes: 'Balanço das cestas distribuídas no mês.' },
  { date: '2026-05-02', formattedDate: '02/Mai/2026', quarter: 2, sabbathNumberInQuarter: 5, department: 'Ministério Jovem', directorName: 'Bruno Oliveira', notes: 'Programa especial direcionado aos universitários.' },
  { date: '2026-05-09', formattedDate: '09/Mai/2026', quarter: 2, sabbathNumberInQuarter: 6, department: 'Ministério da Família', directorName: 'Pr. Ricardo Santos', specialEvent: 'Sábado Especial das Mães', notes: 'Homenagem e momentos especiais com todas as mães.' },
  { date: '2026-05-16', formattedDate: '16/Mai/2026', quarter: 2, sabbathNumberInQuarter: 7, department: 'Mordomia Cristã', directorName: 'Fernando Lima', notes: 'Destaque na generosidade e missão.' },
  { date: '2026-05-23', formattedDate: '23/Mai/2026', quarter: 2, sabbathNumberInQuarter: 8, department: 'Ancionato', directorName: 'Pr. Ricardo Santos', notes: 'Consagração e dedicação da igreja.' },
  { date: '2026-05-30', formattedDate: '30/Mai/2026', quarter: 2, sabbathNumberInQuarter: 9, department: 'Publicações & Evangelismo', directorName: 'Diego Martins', specialEvent: 'Impacto Esperança (Livro)', notes: 'Entrega dos livros missionários pela comunidade.' },
  { date: '2026-06-06', formattedDate: '06/Jun/2026', quarter: 2, sabbathNumberInQuarter: 10, department: 'Desbravadores', directorName: 'Heloísa Ribeiro', notes: 'Investidura das classes e especialidades.' },
  { date: '2026-06-13', formattedDate: '13/Jun/2026', quarter: 2, sabbathNumberInQuarter: 11, department: 'Música & Coral', directorName: 'Camila Fernandes', notes: 'Apresentação musical da Escola Sabatina.' },
  { date: '2026-06-20', formattedDate: '20/Jun/2026', quarter: 2, sabbathNumberInQuarter: 12, department: 'Ministério da Saúde', directorName: 'Juliana Mendes', notes: 'Dicas de hábitos saudáveis e bem-estar espiritual.' },
  { date: '2026-06-27', formattedDate: '27/Jun/2026', quarter: 2, sabbathNumberInQuarter: 13, department: 'Escola Sabatina (Diretoria)', directorName: 'Marcos Silva', specialEvent: '13º Sábado - Oferta Misionária', notes: 'Programa missionário especial e ofertas globais.', targetOffering: 4000 },

  // Q3 2026
  { date: '2026-07-04', formattedDate: '04/Jul/2026', quarter: 3, sabbathNumberInQuarter: 1, department: 'Escola Sabatina & Diretoria', directorName: 'Marcos Silva', notes: 'Lançamento das diretrizes do 3º Trimestre.' },
  { date: '2026-07-11', formattedDate: '11/Jul/2026', quarter: 3, sabbathNumberInQuarter: 2, department: 'Jovens & Pequenos Grupos', directorName: 'Bruno Oliveira', notes: 'Incentivo aos PGs Jovens.' },
  { date: '2026-07-18', formattedDate: '18/Jul/2026', quarter: 3, sabbathNumberInQuarter: 3, department: 'Ancionato', directorName: 'Pr. Ricardo Santos', notes: 'Foco na edificação espiritual.' },
  { date: '2026-07-25', formattedDate: '25/Jul/2026', quarter: 3, sabbathNumberInQuarter: 4, department: 'Ação Solidária Adventista (ASA)', directorName: 'Diego Martins', notes: 'Feira solidária e ações com a comunidade.' },
  { date: '2026-08-01', formattedDate: '01/Ago/2026', quarter: 3, sabbathNumberInQuarter: 5, department: 'Ministério da Criança', directorName: 'Juliana Mendes', notes: 'Participação especial das classes infantis.' },
  { date: '2026-08-08', formattedDate: '08/Ago/2026', quarter: 3, sabbathNumberInQuarter: 6, department: 'Ministério da Família', directorName: 'Pr. Ricardo Santos', specialEvent: 'Sábado Especial dos Pais', notes: 'Programa festivo de homenagem aos pais.' },
  { date: '2026-08-15', formattedDate: '15/Ago/2026', quarter: 3, sabbathNumberInQuarter: 7, department: 'Ministério da Saúde', directorName: 'Juliana Mendes', notes: 'Seminário e testemunhos de saúde integral.' },
  { date: '2026-08-22', formattedDate: '22/Ago/2026', quarter: 3, sabbathNumberInQuarter: 8, department: 'Ministério da Mulher', directorName: 'Adriana Silva', notes: 'Quebrando o Silêncio - Conscientização.' },
  { date: '2026-08-29', formattedDate: '29/Ago/2026', quarter: 3, sabbathNumberInQuarter: 9, department: 'Projeto Maná & ES', directorName: 'Marcos Silva', specialEvent: 'Lançamento do Projeto Maná', notes: 'Divulgação e renovação das assinaturas do Maná.' },
  { date: '2026-09-05', formattedDate: '05/Set/2026', quarter: 3, sabbathNumberInQuarter: 10, department: 'Evangelismo & Ministério Jovem', directorName: 'Bruno Oliveira', specialEvent: 'Batismo da Primavera', notes: 'Cerimônia especial de batismos e recepção de novos membros.' },
  { date: '2026-09-12', formattedDate: '12/Set/2026', quarter: 3, sabbathNumberInQuarter: 11, department: 'Mordomia Cristã', directorName: 'Fernando Lima', notes: 'Relatório das bênçãos do trimestre.' },
  { date: '2026-09-19', formattedDate: '19/Set/2026', quarter: 3, sabbathNumberInQuarter: 12, department: 'Desbravadores', directorName: 'Heloísa Ribeiro', specialEvent: 'Dia Mundial dos Desbravadores', notes: 'Culto oficial do Clube de Desbravadores.' },
  { date: '2026-09-26', formattedDate: '26/Set/2026', quarter: 3, sabbathNumberInQuarter: 13, department: 'Escola Sabatina (Diretoria)', directorName: 'Marcos Silva', specialEvent: '13º Sábado e Festa das Colheitas', notes: 'Grandiosa celebração de 13º Sábado com colheita espiritual.', targetOffering: 4500 },

  // Q4 2026
  { date: '2026-10-03', formattedDate: '03/Out/2026', quarter: 4, sabbathNumberInQuarter: 1, department: 'Escola Sabatina & Diretoria', directorName: 'Marcos Silva', notes: 'Abertura do 4º Trimestre com a equipe docente.' },
  { date: '2026-10-10', formattedDate: '10/Out/2026', quarter: 4, sabbathNumberInQuarter: 2, department: 'Ministério da Criança', directorName: 'Juliana Mendes', notes: 'Comemoração do Dia da Criança na ES.' },
  { date: '2026-10-17', formattedDate: '17/Out/2026', quarter: 4, sabbathNumberInQuarter: 3, department: 'Ação Solidária Adventista (ASA)', directorName: 'Diego Martins', notes: 'Início da campanha do Mutirão de Natal.' },
  { date: '2026-10-24', formattedDate: '24/Out/2026', quarter: 4, sabbathNumberInQuarter: 4, department: 'Ministério da Mulher', directorName: 'Adriana Silva', notes: 'Reunião festiva de gratidão das mulheres.' },
  { date: '2026-10-31', formattedDate: '31/Out/2026', quarter: 4, sabbathNumberInQuarter: 5, department: 'Ancionato & Comunicação', directorName: 'Pr. Ricardo Santos', specialEvent: 'Sábado da Criação', notes: 'Programa temático sobre a Criação Divina.' },
  { date: '2026-11-07', formattedDate: '07/Nov/2026', quarter: 4, sabbathNumberInQuarter: 6, department: 'Ministério Jovem', directorName: 'Bruno Oliveira', notes: 'Testemunhos do projeto Missão Calebe.' },
  { date: '2026-11-14', formattedDate: '14/Nov/2026', quarter: 4, sabbathNumberInQuarter: 7, department: 'Música & Louvor', directorName: 'Camila Fernandes', notes: 'Louvores e cânticos de Ação de Graças.' },
  { date: '2026-11-21', formattedDate: '21/Nov/2026', quarter: 4, sabbathNumberInQuarter: 8, department: 'Desbravadores & Aventureiros', directorName: 'Heloísa Ribeiro', notes: 'Encerramento do ano do clube.' },
  { date: '2026-11-28', formattedDate: '28/Nov/2026', quarter: 4, sabbathNumberInQuarter: 9, department: 'Mordomia Cristã', directorName: 'Fernando Lima', notes: 'Semana de Oração de Mordomia.' },
  { date: '2026-12-05', formattedDate: '05/Dez/2026', quarter: 4, sabbathNumberInQuarter: 10, department: 'Publicações & Sociedade Bíblica', directorName: 'Pr. Ricardo Santos', specialEvent: 'Dia da Bíblia', notes: 'Celebração e valorização da Palavra de Deus.' },
  { date: '2026-12-12', formattedDate: '12/Dez/2026', quarter: 4, sabbathNumberInQuarter: 11, department: 'Ação Solidária Adventista (ASA)', directorName: 'Diego Martins', specialEvent: 'Lançamento Mutirão de Natal', notes: 'Entrega final das cestas do Mutirão de Natal.' },
  { date: '2026-12-19', formattedDate: '19/Dez/2026', quarter: 4, sabbathNumberInQuarter: 12, department: 'Ministério da Família', directorName: 'Pr. Ricardo Santos', notes: 'Gratidão anual pelas famílias da igreja.' },
  { date: '2026-12-26', formattedDate: '26/Dez/2026', quarter: 4, sabbathNumberInQuarter: 13, department: 'Escola Sabatina (Diretoria)', directorName: 'Marcos Silva', specialEvent: '13º Sábado de Fim de Ano', notes: 'Encerramento triunfal do ano letivo de 2026.', targetOffering: 5000 },
];

export const INITIAL_LESSON_CATALOG: LessonCatalogItem[] = [
  { id: 'cat-1', name: 'Lição de Adultos - Aluno', category: 'Adultos', price: 38.0, code: 'CPB-01' },
  { id: 'cat-2', name: 'Lição de Adultos - Professor', category: 'Adultos', price: 45.0, code: 'CPB-02' },
  { id: 'cat-3', name: 'Lição de Jovens - Aluno', category: 'Jovens', price: 38.0, code: 'CPB-03' },
  { id: 'cat-4', name: 'Lição de Jovens - Professor', category: 'Jovens', price: 45.0, code: 'CPB-04' },
  { id: 'cat-5', name: 'Lição de Teens / Adolescentes', category: 'Adolescentes', price: 38.0, code: 'CPB-05' },
  { id: 'cat-6', name: 'Lição dos Juvenis', category: 'Juvenis', price: 38.0, code: 'CPB-06' },
  { id: 'cat-7', name: 'Lição dos Primários', category: 'Primários', price: 38.0, code: 'CPB-07' },
  { id: 'cat-8', name: 'Lição do Jardim da Infância', category: 'Infantil', price: 38.0, code: 'CPB-08' },
  { id: 'cat-9', name: 'Lição do Rol dos Berços', category: 'Bebês / Róis', price: 38.0, code: 'CPB-09' },
  { id: 'cat-10', name: 'Informativo das Missões (Mundial)', category: 'Geral', price: 25.0, code: 'CPB-10' },
  { id: 'cat-11', name: 'Meditação Diária (Inspiração Divina)', category: 'Geral', price: 65.0, code: 'CPB-11' },
];

export const INITIAL_MANA: ManaSubscription[] = [
  {
    id: 'mn-1',
    memberId: 'mb-1',
    memberName: 'Adriana Silva',
    items: [
      { lessonId: 'cat-1', lessonName: 'Lição de Adultos - Aluno', category: 'Adultos', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
    ],
    totalAmount: 38.0,
    amountPaid: 38.0,
    paymentMethod: 'Pix',
    status: 'Quitado',
    quarterlyDelivery: { q1: 'Entregue', q2: 'Pendente', q3: 'Pendente', q4: 'Pendente' },
    deliveryStatus: 'Entregue',
    year: 2026,
    createdAt: '2026-01-05',
    payments: [{ id: 'pm-1', date: '2026-01-05', amount: 38.0, method: 'Pix' }],
  },
  {
    id: 'mn-2',
    memberId: 'mb-4',
    memberName: 'Pr. Ricardo Santos',
    items: [
      { lessonId: 'cat-1', lessonName: 'Lição de Adultos - Aluno', category: 'Adultos', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
      { lessonId: 'cat-2', lessonName: 'Lição de Adultos - Professor', category: 'Adultos', quantity: 1, unitPrice: 45.0, totalPrice: 45.0 },
    ],
    totalAmount: 83.0,
    amountPaid: 83.0,
    paymentMethod: 'Cartão de Crédito',
    status: 'Quitado',
    quarterlyDelivery: { q1: 'Entregue', q2: 'Pendente', q3: 'Pendente', q4: 'Pendente' },
    deliveryStatus: 'Entregue',
    year: 2026,
    createdAt: '2026-01-08',
    payments: [{ id: 'pm-2', date: '2026-01-08', amount: 83.0, method: 'Cartão de Crédito' }],
  },
  {
    id: 'mn-3',
    memberId: 'mb-5',
    memberName: 'Bruno Oliveira',
    items: [
      { lessonId: 'cat-1', lessonName: 'Lição de Adultos - Aluno', category: 'Adultos', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
      { lessonId: 'cat-7', lessonName: 'Lição dos Primários', category: 'Primários', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
    ],
    totalAmount: 76.0,
    amountPaid: 38.0,
    paymentMethod: 'Dinheiro',
    status: 'Parcial',
    quarterlyDelivery: { q1: 'A caminho', q2: 'Pendente', q3: 'Pendente', q4: 'Pendente' },
    deliveryStatus: 'A caminho',
    year: 2026,
    createdAt: '2026-01-10',
    payments: [{ id: 'pm-3', date: '2026-01-10', amount: 38.0, method: 'Dinheiro' }],
  },
  {
    id: 'mn-4',
    memberId: 'mb-7',
    memberName: 'Diego Martins',
    items: [
      { lessonId: 'cat-3', lessonName: 'Lição de Jovens - Aluno', category: 'Jovens', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
    ],
    totalAmount: 38.0,
    amountPaid: 38.0,
    paymentMethod: 'Pix',
    status: 'Quitado',
    quarterlyDelivery: { q1: 'Entregue', q2: 'Pendente', q3: 'Pendente', q4: 'Pendente' },
    deliveryStatus: 'Entregue',
    year: 2026,
    createdAt: '2026-01-12',
    payments: [{ id: 'pm-4', date: '2026-01-12', amount: 38.0, method: 'Pix' }],
  },
  {
    id: 'mn-5',
    memberId: 'mb-11',
    memberName: 'Heloísa Ribeiro',
    items: [
      { lessonId: 'cat-5', lessonName: 'Lição de Teens / Adolescentes', category: 'Adolescentes', quantity: 1, unitPrice: 38.0, totalPrice: 38.0 },
    ],
    totalAmount: 38.0,
    amountPaid: 0.0,
    paymentMethod: 'Pix',
    status: 'Pendente',
    quarterlyDelivery: { q1: 'Pendente', q2: 'Pendente', q3: 'Pendente', q4: 'Pendente' },
    deliveryStatus: 'Pendente',
    year: 2026,
    createdAt: '2026-01-15',
  },
];

export const DEFAULT_CRITERIA_ITEMS = [
  {
    id: 'presence',
    name: 'Presença',
    description: 'Presença física no sábado',
    points: 20,
    enabled: true,
    isCustom: false,
    icon: 'check',
    color: 'emerald' as const,
    systemKey: 'present' as const,
  },
  {
    id: 'punctuality',
    name: 'Pontualidade',
    description: 'Chegada no horário da Escola Sabatina',
    points: 20,
    enabled: true,
    isCustom: false,
    icon: 'clock',
    color: 'blue' as const,
    systemKey: 'punctual' as const,
  },
  {
    id: 'lesson',
    name: 'Estudo da Lição',
    description: 'Estudo diário da Lição da Escola Sabatina',
    points: 20,
    enabled: true,
    isCustom: false,
    icon: 'book',
    color: 'amber' as const,
    systemKey: 'studiedLesson' as const,
  },
  {
    id: 'offering',
    name: 'Oferta de Classe',
    description: 'Participação na oferta da unidade',
    points: 20,
    enabled: true,
    isCustom: false,
    icon: 'dollar',
    color: 'teal' as const,
    systemKey: 'broughtOffering' as const,
  },
  {
    id: 'pg',
    name: 'Pequeno Grupo (PG)',
    description: 'Participação no Pequeno Grupo semanal',
    points: 20,
    enabled: true,
    isCustom: false,
    icon: 'users',
    color: 'purple' as const,
    systemKey: 'attendedPG' as const,
  },
];

export const DEFAULT_CRITERIA_CONFIG: CriteriaPointsConfig = {
  presencePoints: 20,
  punctualityPoints: 20,
  lessonPoints: 20,
  offeringPoints: 20,
  pgPoints: 20,
  items: DEFAULT_CRITERIA_ITEMS,
};

export const INITIAL_ROLLCALL: RollCallRecord[] = [];
